try:
    print(num)
except NameError as result:
    print(result)